CREATE TABLE CATEGORY(
   CAT_SEQ NUMBER NOT NULL,
    SECTION1 VARCHAR2(2) NOT NULL,
    SECTION2 VARCHAR2(2) NOT NULL,
    SECTION3 VARCHAR2(2) NOT NULL,
    SECTION_IFNO VARCHAR2(50) NOT NULL,
    CONSTRAINT CATEGORY_CAT_SEQ_PK PRIMARY KEY(CAT_SEQ)
);

--COMMENT 등록
COMMENT ON TABLE CATEGORY IS '상품 카테고리 관리 테이블';
COMMENT ON COLUMN CATEGORY.SECTION1 IS '대분류';
COMMENT ON COLUMN CATEGORY.SECTION2 IS '중분류';
COMMENT ON COLUMN CATEGORY.SECTION3 IS '소분류';
COMMENT ON COLUMN CATEGORY.SECTION_IFNO IS '상품구분명';

--인덱스 생성
CREATE INDEX CATEGORY_SECTION1_INDEX ON CATEGORY(SECTION1);

