CREATE TABLE ITEM (
	ITEM_ID NUMBER NOT NULL,
	STORE_ID NUMBER NOT NULL,
	ITEM_TITLE VARCHAR2(100) NOT NULL,
	ITEM_INFO VARCHAR2(1000) NOT NULL,
	ITEM_CATEGORY NUMBER NOT NULL,
	ITEM_STATUS VARCHAR2(1)  DEFAULT 'U' NOT NULL,
	EXCHANGE_YN VARCHAR2(1)  DEFAULT 'N' NOT NULL,
	PRICE NUMBER DEFAULT 0 NOT NULL ,
	DELIVERY_PRICE NUMBER DEFAULT 0 NOT NULL ,
	INCLUDE_DELIVERY_PRICE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	TRADE_AREA VARCHAR2(20) DEFAULT '' NOT NULL,
	RELATION_TAG VARCHAR2(50) DEFAULT '',
	STOCK NUMBER DEFAULT 0 NOT NULL ,
	SAFETY_TRADE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL,
	IMG_PATH VARCHAR2(50) NOT NULL,
	NUM_LIKE NUMBER DEFAULT 0 NOT NULL,
	REGISTRATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT ITEM_ITEM_ID_PK PRIMARY KEY(ITEM_ID),
    CONSTRAINT ITEM_STORE_ID_FK FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID),
    CONSTRAINT ITEM_ITEM_CATEGORY_FK FOREIGN KEY(ITEM_CATEGORY) REFERENCES CATEGORY(CAT_SEQ),
    CONSTRAINT ITEM_ITEM_STATUS_CK CHECK(ITEM_STATUS IN ('U', 'N')), --U : 중고 N: 신상
    CONSTRAINT ITEM_EXCHANGE_YN_CK CHECK(EXCHANGE_YN IN ('Y', 'N')),
    CONSTRAINT ITEM_DELIVERY_PRICE_YN_CK CHECK(INCLUDE_DELIVERY_PRICE_YN IN ('Y', 'N')),
    CONSTRAINT ITEM_SAFETY_TRADE_YN_CK CHECK(SAFETY_TRADE_YN IN ('Y', 'N'))
);

--COMMENT 등록
COMMENT ON TABLE ITEM IS '사용자가 등록한 중고물품정보 테이블';
COMMENT ON COLUMN ITEM.ITEM_ID IS '상품ID';
COMMENT ON COLUMN ITEM.STORE_ID IS '등록자ID';
COMMENT ON COLUMN ITEM.ITEM_TITLE IS '상품제목';
COMMENT ON COLUMN ITEM.ITEM_INFO IS '상품설명';
COMMENT ON COLUMN ITEM.ITEM_CATEGORY IS '카테고리번호';
COMMENT ON COLUMN ITEM.ITEM_STATUS IS '상품상태(중고/신상)';
COMMENT ON COLUMN ITEM.EXCHANGE_YN IS '교환가능여부';
COMMENT ON COLUMN ITEM.PRICE IS '가격';
COMMENT ON COLUMN ITEM.DELIVERY_PRICE IS '배송비';
COMMENT ON COLUMN ITEM.INCLUDE_DELIVERY_PRICE_YN IS '배송비포함여부';
COMMENT ON COLUMN ITEM.TRADE_AREA IS '거래지역';
COMMENT ON COLUMN ITEM.RELATION_TAG IS '상품태그';
COMMENT ON COLUMN ITEM.STOCK IS '수량';
COMMENT ON COLUMN ITEM.SAFETY_TRADE_YN IS '안전거래여부';
COMMENT ON COLUMN ITEM.IMG_PATH IS '이미지파일경로';
COMMENT ON COLUMN ITEM.NUM_LIKE IS '찜된횟수';
COMMENT ON COLUMN ITEM.REGISTRATION_DATE IS '등록시간';

--인덱스 생성
CREATE INDEX ITEM_STORE_ID_INDEX ON ITEM(STORE_ID);
CREATE INDEX ITEM_ITEM_CATEGORY_INDEX ON ITEM(ITEM_CATEGORY);
CREATE INDEX ITEM_ITEM_STATUS_INDEX ON ITEM(ITEM_STATUS);
CREATE INDEX ITEM_EXCHANGE_YN_INDEX ON ITEM(EXCHANGE_YN);
CREATE INDEX ITEM_DELIVERY_PRICE_YN_INDEX ON ITEM(INCLUDE_DELIVERY_PRICE_YN);
CREATE INDEX ITEM_TRADE_AREA_INDEX ON ITEM(TRADE_AREA);

--시퀀스 생성
CREATE SEQUENCE ITEM_SEQ INCREMENT BY 1 START WITH 10000000;