CREATE TABLE ITEM_LIKE(
    LIKE_SEQ NUMBER NOT NULL,
    ITEM_ID NUMBER NOT NULL,
    STORE_ID NUMBER NOT NULL,
    LIKE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT ITEM_LIKE_SEQ_PK PRIMARY KEY(LIKE_SEQ),
    CONSTRAINT ITEM_LIKE_ITEM_ID_FK FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID),
    CONSTRAINT ITEM_LIKE_STORE_ID_FK FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID)
);

--COMMENT 등록
COMMENT ON TABLE ITEM_LIKE IS '상품에 대한 찜등록 정보 테이블';
COMMENT ON COLUMN ITEM_LIKE.LIKE_SEQ IS '찜등록번호';
COMMENT ON COLUMN ITEM_LIKE.ITEM_ID IS '상품ID';
COMMENT ON COLUMN ITEM_LIKE.STORE_ID IS '찜등록 사용자ID';
COMMENT ON COLUMN ITEM_LIKE.LIKE_DATE IS '찜등록시간';

--인덱스 생성
CREATE INDEX ITEM_LIKE_STORE_ID_INDEX ON ITEM_LIKE(STORE_ID);
CREATE INDEX ITEM_LIKE_ITEM_ID_INDEX ON ITEM_LIKE(ITEM_ID);

--시퀀스 생성
CREATE SEQUENCE ITEM_LIKE_SEQ INCREMENT BY 1 START WITH 1;