CREATE TABLE ITEM_QUESTION(
    QUESTION_SEQ NUMBER NOT NULL,
    ITEM_ID NUMBER NOT NULL,
    STORE_ID NUMBER NOT NULL,
    QUESTION VARCHAR2(500) DEFAULT '' NOT NULL,
    WRITE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT ITEM_QUESTION_SEQ_PK PRIMARY KEY(QUESTION_SEQ),
    CONSTRAINT ITEM_QUESTION_ITEM_ID_FK FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID),
    CONSTRAINT ITEM_QUESTION_SOTRE_ID_FK FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID)
);

--COMMENT 등록
COMMENT ON TABLE ITEM_QUESTION IS '상품관련 문의내역 정보 테이블';
COMMENT ON COLUMN ITEM_QUESTION.QUESTION_SEQ IS '문의번호';
COMMENT ON COLUMN ITEM_QUESTION.ITEM_ID IS '상품ID';
COMMENT ON COLUMN ITEM_QUESTION.STORE_ID IS '문의자ID';
COMMENT ON COLUMN ITEM_QUESTION.QUESTION IS '문의내용';
COMMENT ON COLUMN ITEM_QUESTION.WRITE_DATE IS '작성일자';

--인덱스 생성
CREATE INDEX ITEM_QUESTION_ITEM_ID_INDEX ON ITEM_QUESTION(ITEM_ID);
CREATE INDEX ITEM_QUESTION_STORE_ID_INDEX ON ITEM_QUESTION(STORE_ID);

--시퀀스 생성
CREATE SEQUENCE ITEM_QUESTION_SEQ INCREMENT BY 1 START WITH 1;