CREATE TABLE STORE (
	STORE_ID NUMBER NOT NULL,
	STORE_NAME VARCHAR2(50) NOT NULL,
	STORE_INFO VARCHAR2(200) DEFAULT '' NOT NULL,
	SNSID VARCHAR2(20) NOT NULL,
	SNSTYPE VARCHAR2(20) NOT NULL,
	MOBILE VARCHAR2(11) NOT NULL,
	MOBILE_OPEN_YN VARCHAR2(1) DEFAULT 'N' NOT NULL,
	CONTACT_START_TIME VARCHAR2(4) DEFAULT '0000'  NOT NULL,
	CONTACT_END_TIME VARCHAR2(4) DEFAULT '0000' NOT NULL,
	AUTHENTICATION_MOBILE VARCHAR2(11),
	AUTHENTICATION_YN VARCHAR2(1) DEFAULT 'N' NOT NULL,
	AREA VARCHAR2(20) NOT NULL,
	ZIP_CODE VARCHAR2(5) NOT NULL,
	BASIC_ADDRESS VARCHAR2(50) NOT NULL,
	DTAIL_ADDRESS VARCHAR2(50) NOT NULL,
	NUM_VISITORS NUMBER DEFAULT 0 NOT NULL ,
	NUM_SALES NUMBER DEFAULT 0 NOT NULL,
	NUM_DELIVERY NUMBER DEFAULT 0 NOT NULL ,
	AVERAGE_POINT NUMBER DEFAULT 0 NOT NULL,
	LAST_LOGIN_TIME DATE,
	ACCOUNT_CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
	LEAVE_DATE DATE,
    CONSTRAINT STORE_STORE_ID_PK PRIMARY KEY(STORE_ID),
    CONSTRAINT SOTRE_STORE_NAME_UQ UNIQUE(STORE_NAME),
    CONSTRAINT STORE_SNSID_SNSTYPE_UQ UNIQUE(SNSID,SNSTYPE),
    CONSTRAINT STORE_MOBILE_OPEN_YN_CK CHECK(MOBILE_OPEN_YN IN ('Y', 'N')),
    CONSTRAINT STORE_AUTHENTICATION_YN_CK CHECK(AUTHENTICATION_YN IN ('Y', 'N'))
);

--COMMENT 등록
COMMENT ON TABLE STORE IS '사용자 정보 테이블';
COMMENT ON COLUMN STORE.STORE_ID IS '상점ID';
COMMENT ON COLUMN STORE.STORE_NAME IS '상점명';
COMMENT ON COLUMN STORE.STORE_INFO IS '상점소개글';
COMMENT ON COLUMN STORE.SNSID IS '간편로그인ID';
COMMENT ON COLUMN STORE.SNSTYPE IS '간편로그인플랫폼';
COMMENT ON COLUMN STORE.MOBILE IS '연락처';
COMMENT ON COLUMN STORE.MOBILE_OPEN_YN IS '연락처공개여부';
COMMENT ON COLUMN STORE.CONTACT_START_TIME IS '연락가능시작시간';
COMMENT ON COLUMN STORE.CONTACT_END_TIME IS '연락가능종료시간';
COMMENT ON COLUMN STORE.AUTHENTICATION_MOBILE IS '본인인증연락처';
COMMENT ON COLUMN STORE.AUTHENTICATION_YN IS '본인인증여부';
COMMENT ON COLUMN STORE.AREA IS '지역';
COMMENT ON COLUMN STORE.ZIP_CODE IS '우편번호';
COMMENT ON COLUMN STORE.BASIC_ADDRESS IS '기본주소';
COMMENT ON COLUMN STORE.DTAIL_ADDRESS IS '상세주소';
COMMENT ON COLUMN STORE.NUM_VISITORS IS '방문자수';
COMMENT ON COLUMN STORE.NUM_SALES IS '판매횟수';
COMMENT ON COLUMN STORE.NUM_DELIVERY IS '택배발송횟수';
COMMENT ON COLUMN STORE.AVERAGE_POINT IS '이용평점';
COMMENT ON COLUMN STORE.LAST_LOGIN_TIME IS '마지막로그인일시';
COMMENT ON COLUMN STORE.ACCOUNT_CREATION_DATE IS '회원등록일시';
COMMENT ON COLUMN STORE.LEAVE_DATE IS '회원탈퇴일시';

--인덱스 생성
CREATE INDEX STORE_SNSTYPE_INDEX ON STORE(SNSTYPE);
CREATE INDEX STORE_AREA_INDEX ON STORE(AREA);
CREATE INDEX STORE_ZIP_CODE_INDEX ON STORE(ZIP_CODE);

--시퀀스 생성
CREATE SEQUENCE STORE_SEQ INCREMENT BY 1 START WITH 10000000;