CREATE TABLE TRADE(
    TRADE_ID NUMBER NOT NULL,
    ITEM_ID NUMBER NOT NULL,
    STORE_ID NUMBER NOT NULL,
    TRADE_STATUS VARCHAR2(1) DEFAULT 'S' NOT NULL,
    QUANTITY NUMBER DEFAULT 0 NOT NULL,
    TOTAL_PRICE NUMBER DEFAULT 0 NOT NULL,
    CONFIRM_DATE DATE,
    CONSTRAINT TRADE_TRADE_ID_PK PRIMARY KEY(TRADE_ID),
    CONSTRAINT TRADE_ITEM_ID_FK FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID),
    CONSTRAINT TRADE_STORE_ID_FK FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID),
    CONSTRAINT TRADE_TRADE_STATUS_CK CHECK(TRADE_STATUS IN ('S', 'R', 'D', 'C')) --SALE(판매중), Reserved(예약중), DELETE(등록삭제), COMPLETE(판매완료)
);

--COMMENT 등록
COMMENT ON TABLE TRADE IS '사용자 간의 거래내역정보 테이블';
COMMENT ON COLUMN TRADE.TRADE_ID IS '거래ID';
COMMENT ON COLUMN TRADE.ITEM_ID IS '상품ID';
COMMENT ON COLUMN TRADE.STORE_ID IS '구매자ID';
COMMENT ON COLUMN TRADE.TRADE_STATUS IS '거래상태';
COMMENT ON COLUMN TRADE.QUANTITY IS '거래수량';
COMMENT ON COLUMN TRADE.TOTAL_PRICE IS '총거래금액';
COMMENT ON COLUMN TRADE.CONFIRM_DATE IS '구매확정일';

--인덱스 생성
CREATE INDEX TRADE_TRADE_ID_INDEX ON TRADE(TRADE_ID);
CREATE INDEX TRADE_ITEM_ID_INDEX ON TRADE(ITEM_ID);
CREATE INDEX TRADE_STORE_ID_INDEX ON TRADE(STORE_ID);
CREATE INDEX TRADE_TRADE_STATUS_INDEX ON TRADE(TRADE_STATUS);

--시퀀스 생성
CREATE SEQUENCE TRADE_SEQ INCREMENT BY 1 START WITH 10000000;